### ISSUE TITLE
Part 3 - Missing solution in the answer

### ISSUE THREAD

**Issue by chengkuangan** [aldettinger/camel-quarkus-workshop#20]
The following dependency is required in `pom.xml`

```
<dependency>
            <groupId>org.apache.camel.quarkus</groupId>
            <artifactId>camel-quarkus-activemq</artifactId>
        </dependency>
```
and the code for `activemq` should looks like the following:
```
from ("file:target/in-orders-recursive?recursive=true")
      .to("activemq:queue:out-orders");
```

**Comment by aldettinger** [comment]
Hey @chengkuangan , well done for progress in the workshop and thanks for sharing this issue :)
Indeed, the dependency is missing in the `answers` branch.

Concerning the route `.to("activemq:queue:out-orders");` it turns out that one should also be able to write `.to("activemq:out-orders");` as `queue` is default as stated in the doc:
`By default, the destinationName is interpreted as a queue name`

Many thanks for sharing :+1:

**Comment by aldettinger** [comment]
Fixed in https://github.com/aldettinger/camel-quarkus-workshop/commit/70be402a8baafc36fc06ba66414fca89292630b7
